# Generated by Django 3.2.25 on 2024-11-11 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='patronym',
            new_name='patronymic',
        ),
    ]
