# Generated by Django 3.2.25 on 2024-11-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_rename_patronym_user_patronymic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20, verbose_name='Телефон'),
        ),
    ]
