# Generated by Django 3.2.25 on 2024-11-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание')),
                ('photo', models.FileField(upload_to='', verbose_name='Фото помещения')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('category', models.CharField(blank=True, choices=[('l', 'Жилые помещения'), ('c', 'Коммерческие помещения'), ('h', 'Отели и гостиницы'), ('b', 'Бары и клубы'), ('s', 'Спа-салоны и салоны красоты'), ('m', 'Медицинские учреждения'), ('o', 'Общественные здания'), ('g', 'Cадовые домики и загородные дома')], default='l', max_length=1, verbose_name='Категория')),
                ('status', models.CharField(blank=True, choices=[('n', 'Новая'), ('w', 'Принято в работу'), ('d', 'Выполнена')], default='n', max_length=1, verbose_name='Статус заявки')),
            ],
        ),
    ]
