# Generated by Django 3.2.25 on 2024-11-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20241114_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.RemoveField(
            model_name='designapplication',
            name='category',
        ),
        migrations.AddField(
            model_name='designapplication',
            name='category',
            field=models.ManyToManyField(to='mysite.Category', verbose_name='Категория'),
        ),
    ]
