# Generated by Django 5.1.3 on 2024-11-14 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20241114_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designapplication',
            options={'permissions': [('can_edit_status', 'Can edit application status')]},
        ),
    ]
