# Generated by Django 3.2.25 on 2024-11-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_alter_designapplication_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='designapplication',
            name='design_comment',
            field=models.TextField(default='', max_length=1000, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='designapplication',
            name='design_photo',
            field=models.FileField(blank=True, upload_to='', verbose_name='Изображение дизайна'),
        ),
        migrations.AlterField(
            model_name='designapplication',
            name='status',
            field=models.CharField(choices=[('n', 'Новая'), ('w', 'Принято в работу'), ('d', 'Выполнена')], default='n', max_length=1, verbose_name='Статус заявки'),
        ),
    ]
