# Generated by Django 3.2.25 on 2024-11-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_auto_20241115_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='designapplication',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='designapplication',
            name='payment_confirmed',
            field=models.BooleanField(default=False, verbose_name='Оплата произведена'),
        ),
    ]
